# fly.toml app configuration file generated for synergy-ch-8-server on 2024-01-04T20:57:34+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "synergy-ch-8-server"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
